# Copyright Louis Dionne 2016
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

shallow_clone: true

os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Debug

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install Ninja
  ############################################################################
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.0-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

  ############################################################################
  # Install a pre-built Clang-cl
  ############################################################################
  - set LLVM_URL="https://www.dropbox.com/s/caol8ihddfwqs31/LLVM-3.7.0-win64.zip?dl=1"
  - appveyor DownloadFile %LLVM_URL% -FileName llvm.zip
  - 7z x llvm.zip -oC:\projects\deps\llvm > nul
  - set PATH=C:\projects\deps\llvm\bin;%PATH%
  - clang-cl -v

  ############################################################################
  # Use a more recent Ruby by default, and install required gems
  ############################################################################
  - dir C:\Ruby21
  - dir C:\Ruby21\bin
  - dir C:\Ruby21\include
  - dir C:\Ruby21\lib
  - dir C:\Ruby21\share
  - set PATH=C:\Ruby21\bin;C:\Ruby21;%PATH%
  - ruby --version
  - gem --version
  - gem install ruby-progressbar tilt


before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\metabench


build_script:
  # Run the example
  - mkdir example\build
  - pushd example\build
  - cmake .. -GNinja -DCMAKE_CXX_COMPILER=clang-cl
  - popd
  - cmake --build example\build --target path.to.benchmark

  # Run the unit tests
  - |
    FOR %dir IN (absolute_paths ctest_target) DO
      mkdir test\%dir%\build
      pushd test\%dir%\build
      cmake .. -GNinja -DCMAKE_CXX_COMPILER=clang-cl
      popd
      cmake --build test\%dir%\build --target check
