# Copyright Louis Dionne 2016
# Copyright Bruno Dutra 2016
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

shallow_clone: true

branches:
  except:
    - /pr\/.+/

build:
  verbosity: detailed

environment:
    matrix:
      # - CMAKE_GENERATOR: "Ninja"
      - CMAKE_GENERATOR: "NMake Makefiles"
      # - CMAKE_GENERATOR: "Unix Makefiles"
      # - CMAKE_GENERATOR: "MSYS Makefiles"

install:
  - if "%CMAKE_GENERATOR%" equ "Ninja" (choco install ninja)
  - if "%CMAKE_GENERATOR%" equ "Unix Makefiles" (set "PATH=C:\cygwin\bin;%PATH%")
  - if "%CMAKE_GENERATOR%" equ "MSYS Makefiles" (set "PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%")

  # Use a more recent Ruby by default.
  - set PATH=C:\Ruby21-x64;C:\Ruby21-x64\bin;%PATH%
  - ruby --version

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\metabench

build_script:
  - mkdir build
  - cd build
  - cmake .. -G"%CMAKE_GENERATOR%"
  - cmake --build .
  - ctest --output-on-failure -VV
